export default Wallpapers = [
    { id: 1, imagesRoute: require(`../res/images/1.jpeg`) },
    { id: 1, imagesRoute: require(`../res/images/1.jpeg`) },
    { id: 1, imagesRoute: require(`../res/images/1.jpeg`) },
    { id: 1, imagesRoute: require(`../res/images/1.jpeg`) },
    { id: 1, imagesRoute: require(`../res/images/1.jpeg`) },
    // { id: 2, imagesRoute: require(`../res/images/2.jpeg`) },
    // { id: 3, imagesRoute: require(`../res/images/3.jpeg`) },
    // { id: 4, imagesRoute: require(`../res/images/4.jpeg`) },
    // { id: 5, imagesRoute: require(`../res/images/5.jpeg`) },
    // { id: 6, imagesRoute: require(`../res/images/6.jpeg`) },
    // { id: 7, imagesRoute: require(`../res/images/7.jpeg`) },
    // { id: 8, imagesRoute: require(`../res/images/8.jpeg`) },
    // { id: 9, imagesRoute: require(`../res/images/9.jpeg`) },
    // { id: 10, imagesRoute: require(`../res/images/10.jpeg`) },
    // { id: 11, imagesRoute: require(`../res/images/11.jpeg`) },
    // { id: 12, imagesRoute: require(`../res/images/12.jpeg`) },
    // { id: 13, imagesRoute: require(`../res/images/13.jpeg`) },
    // { id: 14, imagesRoute: require(`../res/images/14.jpeg`) },
    // { id: 15, imagesRoute: require(`../res/images/15.jpeg`) },
    // { id: 16, imagesRoute: require(`../res/images/16.jpeg`) },
    // { id: 17, imagesRoute: require(`../res/images/17.jpeg`) },
    // { id: 18, imagesRoute: require(`../res/images/18.png`) },
    // { id: 19, imagesRoute: require(`../res/images/19.jpeg`) },
    // { id: 20, imagesRoute: require(`../res/images/20.jpeg`) },
    // { id: 21, imagesRoute: require(`../res/images/21.jpeg`) },
    // { id: 22, imagesRoute: require(`../res/images/22.jpeg`) },
    // { id: 23, imagesRoute: require(`../res/images/23.jpeg`) },
    // { id: 24, imagesRoute: require(`../res/images/24.jpeg`) },
    // { id: 25, imagesRoute: require(`../res/images/25.jpeg`) },
    // { id: 26, imagesRoute: require(`../res/images/26.jpeg`) },
    // { id: 27, imagesRoute: require(`../res/images/27.jpeg`) },
    // { id: 28, imagesRoute: require(`../res/images/28.jpeg`) },
    // { id: 29, imagesRoute: require(`../res/images/29.jpeg`) },
    // { id: 30, imagesRoute: require(`../res/images/30.jpeg`) },
    // { id: 31, imagesRoute: require(`../res/images/31.jpeg`) },
    // { id: 32, imagesRoute: require(`../res/images/32.jpeg`) },
    // { id: 33, imagesRoute: require(`../res/images/33.jpeg`) },
    // { id: 34, imagesRoute: require(`../res/images/34.jpeg`) },
    // { id: 35, imagesRoute: require(`../res/images/35.jpeg`) },
    // { id: 36, imagesRoute: require(`../res/images/36.jpeg`) },
    // { id: 37, imagesRoute: require(`../res/images/37.jpeg`) },
    // { id: 38, imagesRoute: require(`../res/images/38.jpeg`) },
    // { id: 39, imagesRoute: require(`../res/images/39.jpeg`) },
    // { id: 40, imagesRoute: require(`../res/images/40.jpeg`) },
    // { id: 41, imagesRoute: require(`../res/images/41.jpeg`) },
    // { id: 42, imagesRoute: require(`../res/images/42.jpeg`) },
    // { id: 43, imagesRoute: require(`../res/images/43.jpeg`) },
    // { id: 44, imagesRoute: require(`../res/images/44.jpeg`) },
    // { id: 45, imagesRoute: require(`../res/images/45.jpeg`) },
    // { id: 46, imagesRoute: require(`../res/images/46.jpeg`) },
    // { id: 47, imagesRoute: require(`../res/images/47.jpeg`) },
    // { id: 48, imagesRoute: require(`../res/images/48.jpeg`) },
    // { id: 49, imagesRoute: require(`../res/images/49.jpeg`) },
    // { id: 50, imagesRoute: require(`../res/images/50.jpeg`) },
    // { id: 51, imagesRoute: require(`../res/images/51.jpeg`) },
    // { id: 52, imagesRoute: require(`../res/images/52.jpeg`) },
    // { id: 53, imagesRoute: require(`../res/images/53.jpeg`) },
    // { id: 54, imagesRoute: require(`../res/images/54.jpeg`) },
    // { id: 55, imagesRoute: require(`../res/images/55.jpeg`) },
    // { id: 56, imagesRoute: require(`../res/images/56.jpeg`) },
    // { id: 57, imagesRoute: require(`../res/images/57.jpeg`) },
    // { id: 58, imagesRoute: require(`../res/images/58.jpeg`) },
    // { id: 59, imagesRoute: require(`../res/images/59.jpeg`) },
    // { id: 60, imagesRoute: require(`../res/images/60.jpeg`) },
];